/* Autogenerated with kurento-module-creator */

#ifndef __OBJ_DET_OPENCV_IMPL_HPP__
#define __OBJ_DET_OPENCV_IMPL_HPP__

#include "ObjDet.hpp"
#include <EventHandler.hpp>
#include <OpenCVProcess.hpp>

namespace kurento {
namespace module {
namespace objdet {

class ObjDetOpenCVImpl : public virtual OpenCVProcess {

public:
  ObjDetOpenCVImpl();

  virtual ~ObjDetOpenCVImpl() = default;

  virtual void process(cv::Mat &mat);
};

} // namespace objdet
} // namespace module
} // namespace kurento

#endif /*  __OBJ_DET_OPENCV_IMPL_HPP__ */
